name: flutter_google_places
description: Google places autocomplete widgets for flutter. No wrapper, use https://pub.dev/packages/google_maps_webservice
version: 0.5.0
repository: https://github.com/fluttercommunity/flutter_google_places

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  google_api_headers: ^4.5.7
  google_maps_webservice:
    path: ../google_maps_webservice
  http: 1.5.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.8.0

flutter:
  assets:
    - packages/flutter_google_places/assets/google_black.png
    - packages/flutter_google_places/assets/google_white.png
